stages:
  - build
  - publish_docker_image

variables:
  IMG_NAME : "huiwang/encore"
  IMG_TAG : "latest"
  
build-job:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - mvn clean install
  artifacts:
    paths:
     - target/

publish_docker_image_job:
  stage: publish_docker_image
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD https://index.docker.io/v1
    - cp target/*.jar src/main/docker
    - docker build -t $IMG_NAME:$IMG_TAG src/main/docker
    - docker push $IMG_NAME
  only:
    - master